version: '3.7'

networks:
  default:
    name: migrations

services:
  local-db:
    image: mongo:7.0.8
    container_name: localdb
    restart: always
    networks:
      - default
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=p@ssw0rd
    volumes:
      - localdbdata:/data/db
      - ./mongo-entrypoint/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    command: [--auth]

volumes:
  localdbdata:
