name: Database Migration

inputs:
  dbHost:
    required: true
    type: string
  dbPort:
    required: true
    type: string
  DB_USERNAME:
    required: true
    type: string
  DB_PASSWORD:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Mask Password
      shell: bash
      run: echo "::add-mask::${{ inputs.DB_PASSWORD }}"

    - uses: actions/checkout@v3
      with:
        fetch-depth: 2        

    - name: Setup Flyway
      shell: bash
      run: |
        wget -qO- https://download.red-gate.com/maven/release/org/flywaydb/enterprise/flyway-commandline/10.11.0/flyway-commandline-10.11.0-linux-x64.tar.gz | tar -xvz && sudo ln -s `pwd`/flyway-10.11.0/flyway /usr/local/bin 
  
    - name: Run Flyway Migrations
      shell: bash
      env:
        FLYWAY_DRIVER: com.dbschema.MongoJdbcDriver
        FLYWAY_URL: jdbc:mongodb://${{ inputs.dbHost }}:${{ inputs.dbPort }}
        FLYWAY_USER: ${{ inputs.DB_USERNAME }}
        FLYWAY_PASSWORD: ${{ inputs.DB_PASSWORD }}
        FLYWAY_LOCATIONS: filesystem:./db/js
        FLYWAY_SQL_MIGRATION_SUFFIXES: .js
      run: |
        flyway migrate info
